### ISSUE TITLE
Cat Bugs

### ISSUE THREAD

**Issue by Egnale99** [Dokucraft/Dokucraft-High-Bedrock#1]
Hello, I found a bug that Siamese, Tuxedo and Red tabby cats use Light textures after being tamed. I do not know why and how, but I hope it can be fixed. 
![スクリーンショット (223)](https://user-images.githubusercontent.com/64576145/168529660-8c9937a2-e253-49a1-9503-685d255fb8c0.png)

(Pack ID:4cee5896-6af4-4c76-8ad5-d75c3dd0456a)

**Comment by SyndiShanX** [comment]
Fixed, thanks for reporting :)
